definitions:
  domain.CurrencyResponse:
    properties:
      result:
        type: number
    type: object
  domain.ErrorResponse:
    properties:
      error: {}
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a service that helps to calculate get rates
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CurrencyRate API
  version: "1.0"
paths:
  /rates:
    get:
      consumes:
      - application/json
      description: Get Cryptocurrency Rate
      parameters:
      - description: From currency
        in: path
        name: from
        required: true
        type: string
      - description: To currency
        in: path
        name: to
        required: true
        type: string
      - description: Amount to convert
        in: path
        name: from
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CurrencyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get Cryptocurrency Rate
      tags:
      - cryptocurrency
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
